#Wildcard
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: diagon-ally-tls
  namespace: bitwarden
spec:
  secretName: diagon-ally-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: vault-issuer
    kind: Issuer
  commonName: "*.diagon.ally"
  dnsNames:
  - "*.diagon.ally"
  - "diagon.ally"