apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwarden-storage-pv
  labels:
    type: local
    app: bitwarden
spec:
  storageClassName: bitwarden-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/nfs/bitwarden"